# GitHub shared Actions workflow
#
# Reusable workflow: lint, format and type check
# a Node (pnpm) project.
#
# Triggered on:
#   - Call from another repository

name: Node tests

on:
  workflow_call:
    inputs:
      working-directory:
        description: Directory containing the Node project (package.json)
        type: string
        required: true

env:
  CHECKOUT_ACTION: &checkout-action actions/checkout@v7.0.1
  PNPM_SETUP_ACTION: &pnpm-setup-action pnpm/action-setup@v6.0.9
  SETUP_NODE_ACTION: &setup-node-action actions/setup-node@v7.0.0

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: *checkout-action

      - name: Install pnpm
        uses: *pnpm-setup-action
        with:
          version: 10

      - name: Setup Node.js
        uses: *setup-node-action
        with:
          node-version: "24.x"
          check-latest: true
          cache: "pnpm"
          cache-dependency-path: ${{ inputs.working-directory }}/pnpm-lock.yaml

      - name: Install dependencies
        working-directory: ${{ inputs.working-directory }}
        run: pnpm install --frozen-lockfile

      - name: Run ESLint
        working-directory: ${{ inputs.working-directory }}
        run: pnpm lint

      - name: Run Prettier formatting check
        working-directory: ${{ inputs.working-directory }}
        run: pnpm exec prettier --check .

      - name: Run TypeScript type check
        working-directory: ${{ inputs.working-directory }}
        run: pnpm exec tsc --noEmit -p tsconfig.node.json ; pnpm exec tsc --noEmit -p tsconfig.web.json
